spring:
  application:
    name: api-gateway

  cloud:
    gateway:
        routes:
        - id: member
          uri: lb://member-service
          predicates:
            - Path=/api/member/** 
          filters:
            - StripPrefix=1

        - id: class
          uri: lb://class-service
          predicates:
            - Path=/api/class/** 
          filters:
            - StripPrefix=1

        - id: trainer
          uri: lb://trainer-service
          predicates:
            - Path=/api/trainer/** 
          filters:
            - StripPrefix=1

        - id: equipment
          uri: lb://equipment-service
          predicates:
            - Path=/api/equipment/** 
          filters:
            - StripPrefix=1

        - id: listener
          uri: lb://listener-service
          predicates:
            - Path=/api/listener/** 
          filters:
            - StripPrefix=1

        # Rutas de Agregación
        - id: classes-with-trainers
          uri: no://op
          predicates:
            - Path=/api/aggregate/classes-with-trainers
          filters:
            - name: AggregatorGatewayFilterFactory

        - id: trainers-with-classes
          uri: no://op
          predicates:
            - Path=/api/aggregate/trainers-with-classes
          filters:
            - name: AggregatorGatewayFilterFactory

server:
  port: 8761

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: api-gateway