spring:
  application:
    name: api-gateway
    port: 8761

  cloud:
    gateway:
        routes:
        - id: members
          uri: lb://members-service
          predicates:
            - Path=/api/members/** 
          filters:
            - StripPrefix=1

        - id: classes
          uri: lb://classes-service
          predicates:
            - Path=/api/classes/** 
          filters:
            - StripPrefix=1

        - id: trainers
          uri: lb://trainers-service
          predicates:
            - Path=/api/trainers/** 
          filters:
            - StripPrefix=1

        - id: equipment
          uri: lb://equipment-service
          predicates:
            - Path=/api/equipment/** 
          filters:
            - StripPrefix=1

        - id: listener
          uri: lb://listener-service
          predicates:
            - Path=/api/listener/** 
          filters:
            - StripPrefix=1