spring:
  application:
    name: api-gateway

  cloud:
    gateway:
        routes:
        - id: members
          uri: lb://members-service
          predicates:
            - Path=/api/members/** 
          filters:
            - StripPrefix=1

        - id: classes
          uri: lb://classes-service
          predicates:
            - Path=/api/classes/** 
          filters:
            - StripPrefix=1

        - id: trainers
          uri: lb://trainers-service
          predicates:
            - Path=/api/trainers/** 
          filters:
            - StripPrefix=1

        # Ruta especial para agregaci칩n de resumen de miembro
        - id: member-summary
          uri: no://op  # la gestionar치 un filtro/handler (ver secci칩n de agregaci칩n)
          predicates:
            - Path=/api/members/{memberId}/summary